project:
  type: website
  output-dir: docs

website:
#  title: "Mauricio Camargo"
  navbar:
#    background: info
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: ensino.qmd
        text: Ensino
        icon: book
      - href: pesquisa.qmd
        text: Pesquisa
        icon: bug
      - href: extensao.qmd
        text: Extensão
        icon: people
      - href: admin.qmd
        text: Administração
        icon: newspaper
      - href: softwares.qmd
        text: Softwares
        icon: android2
      - href: R-eutilizavel.qmd
        text: R-eutilizáveis
        icon: r-circle
      - href: agenda.qmd
        text: Agenda pública
        icon: calendar
#      - href: hobbies.qmd
#        text: Hobbies
#        icon: alexa

    tools:
      - icon: twitter
        href: https://twitter.com/CamargoFurg
      - icon: github
        menu:
          - text: Página principal
            url:  https://github.com/mauricio-camargo
          - text: Página do site
            url:  https://github.com/mauricio-camargo/mauricio-camargo.github.io

format:
  html:
    theme: cerulean
    css: styles.css
    toc: false

