---
title: "Análise numérica de comunidades ecológicas (Oceanologia-2017)"
output:
  html_document:
    toc: false
---

### Aula 8 (25/10/17)

**Exercício 2**
[Exerc2.pdf](Curso_Comunidades_2017/Exerc2.pdf)  

Planilha para exercício: 
[poluicao.xlsx](Curso_Comunidades_2017/poluicao.xlsx)  

### Aula 7 (11/10/17)

**Aulas**  
[Aula7.pdf](Curso_Comunidades_2017/Aula7.pdf)  

**Códigos do R**  
[Aula7.R](Curso_Comunidades_2017/Aula7.R)


### Aula 6 (27/09/17)

**Aulas**  
[Aula6.pdf](Curso_Comunidades_2017/Aula6.pdf)  

**Planilhas**  
[Abiot.xlsx](Curso_Comunidades_2017/Abiot.xlsx)  

**Códigos do R**  
[Aula6 - Abiot.R](Curso_Comunidades_2017/Aula6 - Abiot.R)


### Aula 5 (13/09/17)

**Aulas**  
[Aula5.pdf](Curso_Comunidades_2017/Aula5.pdf)

**Exercício 1 resolvido**  
[Exerc1_resolvido.Rmd](Curso_Comunidades_2017/Exerc1_resolvido.Rmd)  
[Exerc1_resolvido.pdf](Curso_Comunidades_2017/Exerc1_resolvido.pdf)


### Aula 4 (06/09/17)

**Aulas**  
[Aula4.pdf](Curso_Comunidades_2017/Aula4.pdf)

**Códigos do R**  
[Aula4 - roteiro da aula.R](Curso_Comunidades_2017/Aula4 - roteiro da aula.R)

**Material complementar**  
Como criar relatórios em HTML, PDF ou Word no RStudio usando RMarkdown.  
[Video aula introdutória de Rmarkdown](https://www.youtube.com/watch?v=ZNJTkjetPNU&t=8s)  
[Exemplo_RMarkdown.Rmd](Curso_Comunidades_2017/Exemplo_RMarkdown.Rmd)  
Para gerar relatórios em PDF, instale o [MikTex](http://miktex.org/download)

### Aula 3 (30/08/17)

**Planilhas em Excel**  
[Aula3.xlsx](Curso_Comunidades_2017/Aula3.xlsx) 

**Códigos do R**  
[Aula3.R](Curso_Comunidades_2017/Aula3.R)

**Exercício para o dia 13/09 (e não mais para a próxima semana)**  
[Exercicio1.pdf](Curso_Comunidades_2017/Exercicio1.pdf)

### Aula 2 (26/08/17)

**Aulas**  
[Aula2.pptx](Curso_Comunidades_2017/Aula2.pptx)

**Planilhas em Excel**  
[Aula2.xlsx](Curso_Comunidades_2017/Aula2.xlsx)

**Códigos do R**  
[Aula2.R](Curso_Comunidades_2017/Aula2.R)

### Aula 1 (16/08/17)

**Aulas em PDF**  
[Aula1.pdf](Curso_Comunidades_2017/Aula1.pdf)

**Informações gerais**  
Programas para instalar antes do início do curso:

[R para Windows](https://cran.r-project.org/bin/windows/base)  
[RStudio para Windows](https://www.rstudio.com/products/rstudio/download2/)  
*Nestes sites existem instruções para instalações em outros sistemas operacionais.*

**Material complementar**  
[EcoR - Introdução ao R para ecologia do IB-USP](http://ecologia.ib.usp.br/bie5782/doku.php)  
*Curso online oferecido pelo Instituto de Biologia da USP para ecólogos e áreas afins, com muito material de consulta e exercícios interessantes.*

[Apostilas em português para iniciação ao R](https://cran.r-project.org/other-docs.html#nenglish)  
*Contribuições para o site oficial do R.* 

----

**PLANO DA DISCIPLINA**  

Esta página será atualizada semanalmente, contendo **Informações gerais**, **Aulas em pdf** geradas durante a aula, **Códigos do R** relacionados ao aprendizado prático do R e **Material complementar**, como links de interesse, sugestões de leituras e informações adicionais da matéria da semana.

Os alunos devem treinar os códigos apresentados em casa

**Procedimentos didáticos**  
Aulas teóricas e exercícios semanais no computador.

**Avaliações**  
Vamos pensar nisso!

**Ementa:**  
Teórica: noções de diversidade biológica, comunidades ecológicas e processos ecológicos em comunidades. Amostragem em uma comunidade fictícia. Planilhas de dados abióticos e bióticos. Estatística ecológica em índices univariados de resumo: testes de hipóteses e correlações. Estatística multivariada em comunidades: PCA (planilha de dados abióticos), MDS e PCO (planilha de dados bióticos), análises de agrupamentos e análises canônicas (planilhas abióticas e bióticas).  
Prática: Introdução ao R e RStudio. Estatística descritiva no R. Capacidade gráfica do R. Testes de hipóteses e correlação no R. Tratamento de planilhas no R. Análises multivariadas no R.
