---
title: "Análise numérica de comunidades ecológicas (Oceanologia-2018)"
output:
  html_document:
    toc: false
---

----


### Trabalho Final  

[Trabalho_final.doc](Curso_Comunidades_2018/Trabalho_final.doc)  
[DoubsSpe.xlsx](Curso_Comunidades_2018/DoubsSpe.xlsx)  
[DoubsEnv.xlsx](Curso_Comunidades_2018/DoubsEnv.xlsx)  

### Aula 12 (06/12/18)  

Aula teórica:  
[Aula12.pdf](Curso_Comunidades_2018/Aula12.pdf)  
[Aula12a.pptx](Curso_Comunidades_2018/Aula12a.pptx)  

Aula prática:  
[AulaPCA.R](Curso_Comunidades_2018/AulaPCA.R)  
[Capitais.r](Curso_Comunidades_2018/Capitais.R)  
[cluster.r](Curso_Comunidades_2018/cluster.R)  

Arquivos para baixar:  
[Planilhas_PCA.xlsx](Curso_Comunidades_2018/Planilhas_PCA.xlsx)  
[Distancias_Cidades.xls](Curso_Comunidades_2018/Distancias_Cidades.xls)  
[estuario.xlsx](Curso_Comunidades_2018/estuario.xlsx)


### Aula extra 11 (03/12/18)  

Aula teórica:  
[Aula11.pdf](Curso_Comunidades_2018/Aula11.pdf)  

Aula prática:  
[Aula6.R](Curso_Comunidades_2018/Aula6.R)  
[Aula7.R](Curso_Comunidades_2018/Aula7.R)  

### Aula 10 (01/11/18)  

Aula teórica:  
[Tabelas_Multivariadas.pptx](Curso_Comunidades_2018/Tabelas_Multivariadas.pptx)  

Arquivos para baixar:  
[Abiot.xlsx](Curso_Comunidades_2018/Abiot.xlsx)

### Aula 9 (18/10/18)  

Não houve aula! (SNO)

### Aula 8 (10/10/18)  

Tira dúvidas do conteúdo até aqui ministrado.

### Aula 7 (04/10/18)  

[Aula5a.pdf](Curso_Comunidades_2018/Aula5a.pdf)  
[Aula5a.R](Curso_Comunidades_2018/Aula5a.R)

### Aula 6 (27/09/18)  

Resolução do exercício 1.

[Exerc1_resolvido.Rmd](Curso_Comunidades_2018/Exerc1_resolvido.Rmd)  
[Exerc1_resolvido.pdf](Curso_Comunidades_2018/Exerc1_resolvido.pdf)

### Aula 5 (13/09/18)  
Nessa aula foi demonstrada a utilização de Rmarkdown. Quem quiser rever a aula, existe um vídeo que eu gravei e que pode ser visto [aqui](https://www.youtube.com/watch?v=ZNJTkjetPNU).

**Cabeçalho em Rmarkdown para resolução do exercício 1**  
[Exerc1](Curso_Comunidades_2018/Exerc1_resolvido.Rmd)  


#### Exercício 1 #####
[Exercicio1.pdf](Curso_Comunidades_2018/Exercicio1.pdf)  
[Exerc1.xlsx](Curso_Comunidades_2018/Exerc1.xlsx)     

### Aula 4 (06/09/18)

**Aulas**  
[Aula4.pdf](Curso_Comunidades_2018/Aula4.pdf)  

**Planilhas em Excel**  
[Aula4.xlsx](Curso_Comunidades_2018/Aula4.xlsx)

**Códigos do R**  
[Aula4.R](Curso_Comunidades_2018/Aula4.R)

### Aula 3 (30/08/18)

**Aulas**  
[Aula3.pdf](Curso_Comunidades_2018/Aula3.pdf)  

**Planilhas em Excel**  
[Aula2.xlsx](Curso_Comunidades_2018/Aula2.xlsx)

**Códigos do R**  
[Aula3.R](Curso_Comunidades_2018/Aula3.R)

### Aula 2 (23/08/18)

**Aulas**  
[Aula2.pptx](Curso_Comunidades_2018/Aula2.pptx)

**Planilhas em Excel**  
[Aula2.xlsx](Curso_Comunidades_2018/Aula2.xlsx)

**Códigos do R**  
[Aula2.R](Curso_Comunidades_2018/Aula2.R)

### Aula 1 (16/08/18)

**Aulas em PDF**  
[Aula1.pdf](Curso_Comunidades_2018/Aula1.pdf)  
[Aula1a.pdf](Curso_Comunidades_2018/Aula1.pdf)

**Informações gerais**  
Programas para instalar antes do início do curso:

[R para Windows](https://cran.r-project.org/bin/windows/base)  
[RStudio para Windows](https://www.rstudio.com/products/rstudio/download2/)  
*Nestes sites existem instruções para instalações em outros sistemas operacionais.*

**Material complementar**  
[EcoR - Introdução ao R para ecologia do IB-USP](http://ecologia.ib.usp.br/bie5782/doku.php)  
*Curso online oferecido pelo Instituto de Biologia da USP para ecólogos e áreas afins, com muito material de consulta e exercícios interessantes.*

[Apostilas em português para iniciação ao R](https://cran.r-project.org/other-docs.html#nenglish)  
*Contribuições para o site oficial do R.* 

----

**PLANO DA DISCIPLINA**  

Esta página será atualizada semanalmente, contendo **Informações gerais**, **Aulas em pdf** geradas durante a aula, **Códigos do R** relacionados ao aprendizado prático do R e **Material complementar**, como links de interesse, sugestões de leituras e informações adicionais da matéria da semana.

Os alunos devem treinar os códigos apresentados em casa

**Procedimentos didáticos**  
Aulas teóricas e exercícios semanais no computador.

**Avaliações**  
Será baseada em trabalhos a serem entregues durante a disciplina.

**Ementa:**  
Teórica: noções de diversidade biológica, comunidades ecológicas e processos ecológicos em comunidades. Amostragem em uma comunidade fictícia. Planilhas de dados abióticos e bióticos. Estatística ecológica em índices univariados de resumo: testes de hipóteses e correlações. Estatística multivariada em comunidades: PCA (planilha de dados abióticos), MDS e PCO (planilha de dados bióticos), análises de agrupamentos e análises canônicas (planilhas abióticas e bióticas).  
Prática: Introdução ao R e RStudio. Estatística descritiva no R. Capacidade gráfica do R. Testes de hipóteses e correlação no R. Tratamento de planilhas no R. Análises multivariadas no R.
