---
title: "Estatística (Ciências biológicas - 2016/2)"
output:
  html_document:
    toc: false
---

---

> **Por orientação do comando de greve, as disciplinas que possuem formandos podem ser finalizadas.**

**Assim, vamos retomar a disciplina nessa semana. Falta só uma aula e a última prova, que serão repetidas quando a greve acabar. Mas vou precisar cancelar o trabalho e as notas serão baseadas nas três provas.**

**Nessa sexta-feira teremos aula no horário normal, e logo depois quem quiser pode fazer a segunda chamada da prova, às 18:00h**

**Na semana que vem teremos a última prova.**

****

### **Semana 14 (31/10 a 04/11/2016)**  
**Prova dia 04, sexta-feira, horário de aula**

Lista de exercícios para a prova (banco de questões). Clique [**aqui**](Curso_Estat_Biol/Banco2.pdf)

Conteúdo:   

- Erro padrão e intervalo de confiança
- Testes de hipóteses
- Testes de normalidade e de homocedasticidade
- Teste-t
- ANOVA
- Teste do qui-quadrado

Aula de revisão e resolução dos exercícios na quinta, 16:20h.

***

### **Semana 13 (24 a 28/10/2016)**  
Não haverá aula na sexta-feira devido à Semana acadêmica da biologia.

- A aula extra de quinta-feira (27/10-16:20) foi cancelada porque a defesa civil de Rio Grande recomendou a suspensão das atividades a partir das 15:00h, segundo a página da FURG.

***

### **Semana 12 (17 a 21/10/2016)**  
Não haverá aula na sexta-feira devido à MPU.

***

### **Semana 11 (10 a 14/10/2016)**  
Aula normal na sexta-feira, dia 14, no prédio 6, não sendo necessário laptop.

A prova que seria nessa semana foi adiada para o dia 04/11

- [Aula10.pdf](Curso_Estat_Biol/Aula10.pdf)  

***

### **Semana 10 (03 a 07/10/2016)**  
- [Aula9.pdf](Curso_Estat_Biol/Aula9.pdf)  

***

### **Semana 9 (26 a 30/09/2016)**  
**ATENÇÃO**: CANCELADA a aula desta semana em razão de viagem para defesa de tese de doutorado na UFPR.

A prova que seria realizada no dia 07/10 será adiada.

***

### **Semana 8 (19 a 23/09/2016)**  
- **Aulas em pdf**  
[Aula8.pdf](Curso_Estat_Biol/Aula8.pdf)  


[Notas da primeira prova](https://dl.dropboxusercontent.com/u/85015358/Notas1.pdf)*: dúvidas sobre a prova logo após a aula de sexta.*  
[Estatística descritiva das notas da prova](Curso_Estat_Biol/Notas.html)

````
Prova 2a chamada de novo: Dia 22/09, quinta-feira, às 17:00h, no prédio 6. 
````

---

### **Semana 7 (12 a 16/09/2016)**  
- **Aulas em pdf**  
[Aula7.pdf](Curso_Estat_Biol/Aula7.pdf)  

---

### **Semana 6 (05 a 09/09/2016)**  
- **Aulas em pdf**  
[Aula6.pdf](Curso_Estat_Biol/Aula6.pdf)  

````
Prova 2a chamada: Dia 08/09, quinta-feira, 17:00h, no prédio 6.
````

---

### **Semana 5 (29/08 a 02/09/2016)**
- **Aulas em pdf**  
[Aula5 - Continuacao da Aula3.pdf](Curso_Estat_Biol/Aula5 - Continuacao da Aula3.pdf)  

> #### **Prova dia 02, sexta-feira**
Conteúdo baseado neste 
[**Banco de questões**](Curso_Estat_Biol/Banco1.pdf).  
*Aula extra de revisão:* **Quinta-feira, 14:30h**  
Nesta semana não haverá aula para o Grupo de Matemática.

---

### **Semana 4 (22 a 26/08/2016)**
- **Aulas em pdf**  
[Aula4.pdf](Curso_Estat_Biol/Aula4.pdf)  

- **Códigos do R**  
[Enquete.R](Curso_Estat_Biol/Enquete.R)

- **Arquivo do Excel para abrir no R**  
[enquete.xls](Curso_Estat_Biol/Enquete.xls)  

##### **Grupo de matemática** (Quinta, 27)  
Alunos presentes: Seis  
Material usado:  
- [Distribuição de frequências](Curso_Estat_Biol/1-Int-DistFreq.pdf)  
- [Somatórios](Curso_Estat_Biol/2-Inf-Somatorio.pdf)  
- [Artigo interessante para leitura](Curso_Estat_Biol/3-artigo1.pdf)  

##### **Grupo de matemática** (Terça, 25)  
Alunos presentes: *Zero*  

----

### **Semana 3 (15 a 19/08/2016)**

- **Aulas em pdf**  
[Aula3.pdf](Curso_Estat_Biol/Aula3.pdf)  

- **Códigos do R**  
[Aula2.R](Curso_Estat_Biol/aula2.R)

----

### **Semana 2 (08 a 12/08/2016)**

- **Programas para instalar antes da aula:**  
[R para Windows](https://cran.r-project.org/bin/windows/base)  
[RStudio para Windows](https://www.rstudio.com/products/rstudio/download2/)

- **Aulas em pdf**  
[Aula1.pdf](Curso_Estat_Biol/Aula1.pdf)  
[Aula2.pdf](Curso_Estat_Biol/Aula2.pdf)

- **Códigos do R**  
[Aula1.R](Curso_Estat_Biol/aula2.R)

----

### **Semana 1 - (01 a 05/08/2016)**

- Por que estatística?
- Conceito de população e amostra
- Amostragem
- Tipos de dados

----

### **Atendimento aos alunos**
Atendimentos na base oceanográfica (Laboratório de Ecologia de Comunidades Bentônicas), nos seguintes horários:  

- Terça-feira, 09:15h até 11:00h  
- Quinta-feira, 09:15h até 11:00h  

-----

### **Opcional: Grupo de matemática**  

Para aqueles que querem entender melhor a estatística através da matémática, o grupo de matemática se reunirá nos seguintes horários:

- Quintas-feiras, 15:30h, sala 6106.  
 
----

### **Ementa**  
Estimação de parâmetros. Teste de hipóteses. Análise de correlação e regressão. Experimentos multinomiais e tabelas de contingência. Análise de variância.  

#### **Conteúdo prático**  
Familiarização com o R e o RStudio. Entrada de dados. Cálculos simples. Vetores e cálculos com vetores. Gráficos simples. Análises estatísticas dadas em aulas teóricas.

#### **Conteúdo da revisão**
População e amostra. Amostragem. Tipos de dados. Distribuição de frequência. Ajustes probabilísticos a uma distribuição de frequência. Medidas de tendência central. Medidas de dispersão.  

---

### **Avaliações**

As avaliações constarão de 4 pequenas provas escritas e um relatório prático escrito no RStudio.

As provas escritas serão aplicadas nos primeiros 50 minutos da aula, contendo 3 ou 4 perguntas simples. 

O relatório prático será em grupos de no máximo 3 pessoas. As diretrizes para o trabalho serão disponibilizadas em breve.

<!-- Centralização das colunas
No centro
  Avaliação       Data             Peso
--------------- ---------------- --------------
À direita
Avaliação       Data             Peso
--------------- ---------------- --------------

-->
  Avaliação         Data           Peso
--------------- ---------------- --------------
Prova escrita 1 02/set           1,5
Prova escrita 2 07/out           1,5
Prova escrita 3 04/nov           1,5
Prova escrita 4 02/dez           1,5
Trabalho no R   25/nov (entrega) 4,0
                                 **Total=10,0**

Table: Resumo das avaliações

<!--
Pode er tb com pacote pander
```{r echo = FALSE}
library(pander)
a=c(1,2,3,4)
b=c('A','B','C','D')
d=c('qwe','Betr','Cert','Drty')
x=data.frame(a,b)
rownames(x)=d
pander(x)
``` 
-->
