---
title: "Estatística univariada para estudos de distribuição espacial e temporal"
output:
  html_document:
    toc: false
---

---- 

Planilha de notas:  
[Notas Univariada 2018.xlsx](Curso_Univar_PG_2018/Notas Univariada 2018.xlsx)  

### **Semana 7 - (Aula em 27/11/2018)**  

**Seminário: Artigos para escolher**  
[Morrisey Espacial 1992.pdf](Curso_Univar_PG_2018/Morrisey Espacial 1992.pdf)  
[Morrisey Temporal 1992.pdf](Curso_Univar_PG_2018/Morrisey Temporal 1992.pdf)   
[Hughes et al. 1999.pdf](Curso_Univar_PG_2018/Hughes et al. 1999.pdf)   
[Crowe 1999.pdf](Curso_Univar_PG_2018/Crowe 1999.pdf)  
[Olabarria 2009.pdf](Curso_Univar_PG_2018/Olabarria 2009.pdf)  
[Souza et al.2016.pdf](Curso_Univar_PG_2018/Souza et al.2016.pdf)  
[Camargo et al. 2017.pdf](Curso_Univar_PG_2018/Camargo et al. 2017.pdf)  

[**Outros artigos pré-aprovados para o seminário**](https://mauricio-camargo.github.io/artigos_seminarios.html).

### **Semana 5 e 6 - (Aula em 19 e 20/11/2018)**

**Aulas teóricas**  
[Aula5.pdf](Curso_Univar_PG_2018/Aula5.pdf)  
[Aula6.pdf](Curso_Univar_PG_2018/Aula6.pdf)  

**Aulas práticas no R**  
[RegMult.r](Curso_Univar_PG_2018/RegMult.r)  
[Aula5.R](Curso_Univar_PG_2018/Aula5.R)  
[Aula6.R](Curso_Univar_PG_2018/Aula6.R)  

**Planilhas**  
[Costao.xlsx](Curso_Univar_PG_2018/Costao.xlsx)  
[Peixes.xlsx](Curso_Univar_PG_2018/Peixes.xlsx)  
[planilha_dados.xlsx](Curso_Univar_PG_2018/planilha_dados.xlsx)  
**Artigo para leitura**  
[Underwood 1997-metodo.doc](Curso_Univar_PG_2018/Underwood 1997-metodo.doc)  

**Artigo para resenha (entregar dia 27/11)**  
[Morrison - 2002 - Nested factors.pdf](Curso_Univar_PG_2018/Morrison - 2002 - Nested factors.pdf)  

### **Semana 4 - (Aula em 06/11/2018)**

**Aulas práticas no R**  
[Aula4.R](Curso_Univar_PG_2018/Aula4.R)  

**Aula teórica**  
[Aula4.pdf](Curso_Univar_PG_2018/Aula4.pdf)  

**Arquivo para resenha**  
[REPLICATE OR LIE - Prosser.pdf](Curso_Univar_PG_2018/REPLICATE OR LIE - Prosser.pdf)

### **Semana 3 - (Aula em 30/10/2018)**

**Aula teórica**  
[Aula3.pdf](Curso_Univar_PG_2018/Aula3.pdf)  

**Baixar arquivos para a aula**  
[planilha1.xlsx](Curso_Univar_PG_2018/planilha1.xlsx)  
[enquete.xls](Curso_Univar_PG_2018/enquete.xls)  

**Aulas práticas no R**  
[Aula3.R](Curso_Univar_PG_2018/Aula3.R)  
[Aula2.R](Curso_Univar_PG_2018/Aula2.R)  


### **Semana 2 - (Aula em 16/10/2018)**

**Baixar arquivo para a aula**  
[Desvendando R.pptx](Curso_Univar_PG_2018/Desvendando R.pptx)

**Aula prática no R**  
[Aula1.R](Curso_Univar_PG_2018/Aula1.R)

### **Semana 1 - (Aula em 09/10/2018)**

**Aulas**  
[Aula1.ppt](Curso_Univar_PG_2018/Aula1.ppt)  

**Artigo para resenha (entregar dia 23/10) - *Atenção para nova data* **  
[Error Bars in Experiemental Biology.pdf](Curso_Univar_PG/Error Bars in Experiemental Biology.pdf)

----

**- Programas para instalar antes da aula:**   

[R para Windows](https://cran.r-project.org/bin/windows/base)  
[RStudio para Windows](https://www.rstudio.com/products/rstudio/download2/) 

Nestes sites existem instruções para instalações em outros sistemas operacionais.

----

**Ementa:**

Este curso é baseado em seis aulas teóricas e quatro aulas práticas:

1. Introdução ao R e ao RStudio. O R como calculadora de luxo. Instalação de pacotes do R. Entrada de dados e importação de planilhas do Excel. Estatística descritiva: medidas de tendência central e de posição, medidas de dispersão. Gráficos básicos: gráficos de dispersão, boxplots e gráficos de barras com medidas de dispersão. Distribuições estatísticas e histogramas. Inferência estatística. Regressão e correlação. ANOVA de um fator (Teoria).
Biblio: 1 e 5

2. A lógica do pensamento científico. Modelos. Modelos lineares. Modelos lineares gerais: Regressão linear e ANOVA (Teoria e prática no R).
Biblio: 2 e 4

3. Métodos clássicos de regressão linear simples e múltipla e de ANOVA multifatorial (Teoria e prática no R).
Biblio: 4, 3 e 2

4. Fatores fixos e aleatórios. Delineamentos hierárquicos e ortogonais clássicos e suas aplicações universais. Modelos complexos e suas aplicações (Teoria e prática no R).
Biblio: 4

5. Diversos sabores de ANOVA em ecologia e suas aplicações. Pseudoreplicação e modelos mistos de ANOVA (Teoria e prática no R).
Biblio:4, 3 e 2

6. Aplicações de ANOVA no espaço-tempo (Teoria). 
Biblio: 1,2,3,4 e 5

**Bibliografia**

1. Gottelli, N.; Ellison, A.M. *A primer of ecological statistics.* 2013. ISBN 9781605351919

2. Quinn, G.P.; Keough, M. *Experimental design and data analysis for biologists.* 2002. ISBN 0521009766

3. Sokal, R.R and Rohlf, F,J. Biometry: *The Principles and Practices of Statistics in Biological Research.* 1995. ISBN 0716724111.

4. Underwood, A.J. *Experiments in ecology – their logical design and interpretation using analysis of variance.* 1997. ISBN 0521556961.

5. Zuur, A.F. ; Leno, E.N. ; Meesters, E.W.G. *A beginner’s guide to R.* 2009. ISBN 9780387938363.
