---
#title: "Ensino"
lang: pt-br
engine: knitr
---

## Disciplinas - FURG

::: aside
**Disciplinas em processo de criação para 2026:**

*Como fazer ciência* (Graduação em Oceanologia) 

:::

### **2026 (Atual)**

- **Biodiversidade de invertebrados marinhos - Anelídeos poliquetas**
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a Julho de 2026

### **2025**

#### Graduação

- **Lógica da programação e análise de dados em R** 
  - Cursos oferecidos: *Oceanologia*
  - Período: Agosto a Dezembro de 2025

- **Biodiversidade de invertebrados marinhos - Anelídeos poliquetas**<!--(https://mauricio-camargo.github.io/Biodiversidade2025/))-->
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a Julho de 2025

#### Minicurso

- **R raiz!** <!--([arquivo R](docs/R-raiz.R))-->

#### Pós-graduação

- **Delineamentos experimentais em ecologia**   

  - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
  - Período: Outubro a Dezembro de 2025.


### **2024**

#### Graduação

- **Biodiversidade de invertebrados marinhos - Anelídeos poliquetas**<!--(https://mauricio-camargo.github.io/Biodiversidade2024/))-->
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a Julho de 2024

#### Pós-graduação

- **Reprodutibilidade científica no R**<!--(https://mauricio-camargo.github.io/reprodu2024/)-->
  - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
  - Período: Julho a Outubro de 2024


- **Delineamento Experimental em Ecologia**
  - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
  - Período: Outubro a Dezembro de 2024.


### **2023**

#### Graduação

- **Programação em Python e R**
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a julho de 2023

- **Biodiversidade de invertebrados marinhos - Anelídeos poliquetas**
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a julho de 2023

- **Monitoramento da Contaminação e Poluição Aquática** (4h) 
  - Cursos oferecidos: *Oceanologia*
  - Período: Outubro de 2023

#### Pós-graduação

- **Reprodutibilidade científica no R**
    - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
    - Período: Outubro e novembro de 2023

- **Delineamento Experimental em Ecologia**
    - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
    - Período: Outubro e novembro de 2023

### **2022**

#### Graduação

- **Programação em Python e R**
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a julho de 2022

#### Pós-graduação

- **Delineamento Experimental em Ecologia**
  - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
  - Período: Outubro e novembro de 2022

### **2021**

#### Graduação

- **Programação em Python e R**
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a julho de 2021

#### Pós-graduação

- **Delineamento Experimental em Ecologia**
  - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
  - Período: Outubro e novembro de 2021

### **2020**

#### Graduação

- **Programação em Python e R**
  - Cursos oferecidos: *Oceanologia*
  - Período: Março a julho de 2020

#### Pós-graduação

- **Delineamento Experimental em Ecologia**
  - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
  - Período: Outubro e novembro de 2020

### **2019**

#### Pós-graduação

- **Delineamento Experimental em Ecologia**
  - Cursos oferecidos: *Pós-graduações diversas (PPGAMB, PPGOB, PPGO)*
  - Período: Outubro e novembro de 2019

### **2018**

#### Graduação

- **Análise numérica de comunidades  ecológicas**
  - Cursos oferecidos: *Oceanologia e ouvintes da pós-graduação*
  - Período: Agosto a novembro de 2018

  <!-- (curso_comunidades_2018.html) -->
 
#### Pós-graduação

- **Estatística univariada para estudos de distribuição espacial e temporal**
  - Cursos oferecidos: *Pós-graduações diversas*
  - Período: Outubro e novembro de 2018

<!-- curso_univariada_2018.html) --> 


### **2017**

#### Graduação

 - **Análise numérica de comunidades  ecológicas**   
    + Cursos oferecidos: *Oceanologia e ouvintes da pós-graduação*
    + Período: Agosto a novembro de 2017

#### Pós-graduação

- **Estatística univariada para estudos de distribuição espacial e temporal**  

    + Cursos oferecidos: *Pós-graduações diversas*
    + Período: Outubro e novembro de 2017

### **2016**

#### Graduação

- **Estatística**  
    + Curso oferecido: *Ciências Biológicas*  
    + Período: Agosto a novembro de 2016

- **Ciências do ambiente**
    + Cursos oferecidos: *Engenharias*  
    + Período: Agosto a novembro de 2016  

 - **Análise numérica de comunidades  ecológicas**   
    + Cursos oferecidos: *Oceanologia e ouvintes da pós-graduação*
    + Período: Agosto a novembro de 2016

#### Pós-graduação

- **Estatística univariada para estudos de distribuição espacial e temporal**
    + Cursos oferecidos: *Pós-graduações diversas*
    + Período: Outubro e novembro de 2016

### **2015**

#### Pós-graduação

- **Estatística univariada para estudos de distribuição espacial e temporal**
    + Cursos oferecidos: *Pós-graduações diversas*
    + Período: Outubro e novembro de 2015

### **2014 - 2000**

Disciplinas ministradas no Centro de Estudos do Mar da UFPR:  

**Graduação** (Oceanografia e Aquicultura)

- Análise multivariada e de séries temporais (ministrada sozinho em 2002, logo após a defesa do doutorado) 
- Introdução à estatística (Oceanografia e Aquicultura) 
- Inferência estatística (Oceanografia)
- Planejamento amostral e experimental (Oceanografia)
- Oficina de pesquisa I, II e IV (Oceanografia)
- Biodiversidade de invertebrados - Poliquetas (Oceanografia)
- Programação em Pascal e SQL (Oceanografia)

**Pós-graduação** (PGSISCO e PGZOO da UFPR)

- Ecologia numérica (PGSISCO)
- Análise multivariada (PGSISCO)
- Estatística básica (PGZOO)
