---
title: "Ensino"
output:
  html_document:
    toc: false
---

----

## Disciplinas - FURG

### **2017**

#### Graduação

 - [**Análise numérica de comunidades  ecológicas**](curso_comunidades_2017.html) 
    + Cursos oferecidos: *Oceanologia e ouvintes da pós-graduação*
    + Período: Agosto a novembro de 2017

#### Pós-graduação

- **Estatística univariada para estudos de distribuição espacial e temporal**
    + Cursos oferecidos: *Pós-graduações diversas*
    + Período: Outubro e novembro de 2017

### **2016**

#### Graduação

- ***Estatística***  
    + Curso oferecido: *Ciências Biológicas*  
    + Período: Agosto a novembro de 2016

- **Ciências do ambiente**
    + Cursos oferecidos: *Engenharias*  
    + Período: Agosto a novembro de 2016  

 - **Análise numérica de comunidades  ecológicas**   
    + Cursos oferecidos: *Oceanologia e ouvintes da pós-graduação*
    + Período: Agosto a novembro de 2016

#### Pós-graduação

- **Estatística univariada para estudos de distribuição espacial e temporal**
    + Cursos oferecidos: *Pós-graduações diversas*
    + Período: Outubro e novembro de 2016

### **2015**

#### Pós-graduação

- **Estatística univariada para estudos de distribuição espacial e temporal**
    + Cursos oferecidos: *Pós-graduações diversas*
    + Período: Outubro e novembro de 2015

### **2014 - 2004**

Disciplinas ministradas no Centro de Estudos do Mar da UFPR:  

**Graduação**

- Introdução à estatística
- Inferência estatística
- Análise multivariada
- Planejamento amostral e experimental

**Pós-graduação**

- Ecologia numérica
- Análise multivariada