---
#title: "hobbies"
---

## Meus 11 hobbies (2026)

Em 2021 (53 anos) decidi elencar 10 hobbies e praticá-los semanalmente. Apareceram 11. Foi a melhor decisão da minha vida. Demorei alguns anos para finalizar a lista, que ficou pronta e testada em 2025.  

Esse é o ranking atual (**2026**) dos meus 11 hobbies:

<details>
<summary><strong>1. Corrida</strong></summary>
- A corrida foi meu primeiro esporte. Tive a sorte de entrar em uma escola (Marista de Brasília) que tinha uma equipe de atletismo. Aos 12 anos comecei a treinar sério e participei de competições até os 17 anos.  
Corri praticamente minha vida toda, mas começei a ter lesões em 2022 (54 anos), por causa dos exageros em uma corrida de 24 km em estrada de terra, na ilha dos marinheiros, em Rio grande.  
Passei, então, a praticar os outros esportes (BT, vôlei e skate), que substituíram a corrida como aeróbico.  

- Coisa boa da vida: poder correr pelo menos 2x na semana, mesmo que de leve. Correr me faz muito bem.  

- Estou no Strava (<https://www.strava.com/athletes/mauriciocamargo>)

</details>

<details>
<summary><strong>2. Bike</strong></summary>
- Semmmmpre pedalei. Fiz muitas viagens de bike.  
Quando comecei a ter lesões por causa da corrida, o pedal me salvou. O pedal me deu sobrevida à corrida, pois é um complemento dela. Pedal cura joelho, acreditem!   

- Coisa boa da vida: fazer uma pedalada longa em mountain bike.  
</details>

<details>
<summary><strong>3. Vôlei de praia</strong></summary>

- Redescobri o vôlei em Maio de 2024 (56 anos), relembrando a adolescência.    

- Coisa boa da vida: fazer aula de vôlei e ter a turminha do vôlei de domingo.
</details>

<details>
<summary><strong>4. Skate (surfskate / simulador)
</strong></summary>

- Redescobri o skate (após a infância) em Março de 2025 (57 anos), depois de assistir uma mulher circulando na pista do Cassino sem tirar as rodas do chão. Fiquei sabendo que aquele era um novo tipo de skate chamado simulador de surf. Comprei imediatamente e me apaixonei compulsivamente. Fiz aulas e aprendi rapidinho a fazer todo o circuito da minha querida pista de skate do Cassino, que está no [Youtube](https://www.youtube.com/shorts/tBj-65xjIow). 

- Coisa boa da vida: andar de skate todo dia...

</details>

<details>
<summary><strong>5. Beach Tennis (BT)</strong></summary>

- Descobri o BT em Maio de 2025 (57 anos).  
Me apaixonei perdidamente e me confesso viciado.  
Jogo há pouco tempo, mas (acho que) não sou mais (tão) iniciante. 

- Coisa boa na vida: ter a turminha do BT de terça e sábado, mais a aula de sexta.  

</details>

<details>
<summary><strong>6. Guitarra</strong></summary>
- Toquei guitarra dos 12 aos 23 anos, depois parei.  
Voltei para o violão aos 40, tentando cantar.  
Em 2018, no meu aniversário de 50 anos, me dei de presente uma Fender Stracocaster, que era meu sonho de adolescente.

- Coisa boa da vida: tirar um novo solo (tem tudo no [YouTube](https://www.youtube.com/@mauriciocamargofurg)).
</details>

<details>
<summary><strong>7. Moto</strong></summary>
- Tive uma XL-250R em 1992 (24 anos), de um carburador, que era um tratorzinho. Com ela rodei os estados do PR e SC. Em 2024 (56 anos) comprei uma RE Meteor 350, que tinha um ronco muito parecido com o da XL. Vendi, mas logo, logo vou comprar uma RE Himalayan 450.

- Coisa boa da vida: fazer um bate e volta de Rio Grande para PoA de moto! (Estou sem moto agora, mas por pouco tempo).

</details>

<details>
<summary><strong>8. Xadrez</strong></summary>
- Aprendi na infância, com a amigos. Joguei muito na adolescência, mas não estudava. Ficou adormecido em mim, até que descobri em 2018 (50 anos) o site <https://www.chessfriends.com>. Comecei a jogar com gente do mundo todo, de todos os níveis, e isso mudou tudo. Hoje estudo um pouco e vivo tentando detonar uns russos de 12-13 anos, que são o capeta no xadrez.

- Coisa boa da vida: detonar um russo de 12-13 anos no xadrez online! 

</details>

<details>
<summary><strong>9. Horta e compostagem</strong></summary>
- Faço compostagem há muitos anos. Toda a matéria orgânica da minha casa vai para as minhocas que produzem muito adubo e chorume. As minhocas servem até para aulas de Annelida! Hoje tenho uma horta circular de cerca de $1 m^2$ que abriga 21 espécies de ervas, temperos e folhas, abastecida pelo adubo da minha compostagem.  

- Coisa boa da vida: plantar meus próprios temperos.

</details>

<details>
<summary><strong>10. Cozinha</strong></summary>

- Aprendi tardiamente a cozinhar. Enquanto eu tinha pai, mãe e um irmão para me ensinar, aprendi bem pouco, de burro!  Tive que aprender depois de velho, aos 40, com ajuda do meu cérebro na cozinha (Eunice), e de livros, muitos livros de culinária. 

- Hoje eu amo cozinhar, mesmo com minhas deficiências de base culinária e esquecimentos, que aprendi a conviver e que os outros são obrigados a me perdoar!  

- Coisa boa da vida: acertar as descidas de todas as pizzas no forno a lenha sem cagar o forno.

</details>

<details>
<summary><strong>11. Programação</strong></summary>
- A programação entrou na minha vida por necessidade acadêmica, na Bélgica, ainda em 1993. Na época estava surgindo o Delphi, uma implementação da linguagem Pascal compilada, ou seja, rápida como um raio. Me apaixonei e fiz dezenas de programas comerciais, acadêmicos e open source com ele. Mais tarde comecei a programar em Lazarus, uma alternativa open source ao Delphi. Hoje Lazarus é minha paixão, e disponibilizo diversos programas open source no meu [Github](https://github.com/mauricio-camargo). 

- Programação em R também é minha paixão. Ano passado dei uma disciplina de Introdução à programação com o R, que funcionou muito bem. Mas R não é um hobby como o Lazarus, que é capaz de criar programas genéricos, que servem para qualquer coisa. 

</details>


<!--
  De vez em quando esqueço de um ou de outro hobby, mas a saudade sempre aperta e nunca fico muito tempo longe de nenhum.
-->


