---
#title: "Pesquisa"
lang: pt-br
engine: knitr
---

```{css,  echo=FALSE}
.justify {
 text-align:
justify !important}
```

## Publicações


:::{.justify}
- [SANTOS, MARCOS EDUARDO MIRANDA ; SPENASSATO, DÉBORA ; DE AZAMBUJA, ANA MARIA VOLKMER ; NUNES, JORGE LUIZ SILVA ; DE CAMARGO, MAURÍCIO GARCIA . Trends for Research on Hard Substrate Colonization by Meiofauna. Marine Ecology-An Evolutionary Perspective, v. 46, p. e70010, 2025.](http://dx.doi.org/10.1111/maec.70010)

- [ROCHA, ELIS BRANDÃO ; DA COSTA MACHADO, EUNICE ; DE CAMARGO, MAURÍCIO GARCIA ; DE REZENDE, CARLOS EDUARDO ; GATTS, PEDRO VIANNA ; MENDES, CARLOS RAFAEL BORGES ; COSTA, RAUL RODRIGO ; WALLNER-KERSANACH, MÔNICA ; MATA, MAURICIO M. ; KERR, RODRIGO . Distribution, composition, and drivers of suspended particulate organic matter in the Gerlache Strait, Northern Antarctic Peninsula. DEEP-SEA RESEARCH PART I-OCEANOGRAPHIC RESEARCH PAPERS, v. 224, p. 104559, 2025.](http://dx.doi.org/10.1016/j.dsr.2025.104559)  

- [BALBELA, CAROLINE CARNEIRO ; SOROLDONI, SANYE ; FERNANDES, ANDREIA NEVES ; DE CAMARGO, MAURÍCIO GARCIA ; KESSLER, FELIPE ; PINHO, GRASIELA LOPES LEÃES . Assessing the impact of simulated ocean acidification on the photodegradation of selected microplastics. MARINE POLLUTION BULLETIN, v. 207, p. 116854, 2024.](http://dx.doi.org/10.1016/j.marpolbul.2024.116854)

- [VASCONCELLOS, DAVI M ; BAINY, MARA CRS ; CAMARGO, MAURÍCIO G ; TEIXEIRA BONECKER, ANA CRISTINA ; COSTA BONECKER, SÉRGIO LUIS ; HAIMOVICI, MANUEL . Cephalopod paralarvae in a tropical Brazilian basin: distribution throughout oceanographic features and water masses. BULLETIN OF MARINE SCIENCE, v. xxx, p. 1, 2024.](http://dx.doi.org/10.5343/bms.2023.0171)

- [BORDIN, LUÍS HENRIQUE ; DA COSTA MACHADO, EUNICE ; MENDES, CARLOS RAFAEL BORGES ; FERNANDES, ELISA HELENA LEÃO ; DE CAMARGO, MAURÍCIO GARCIA . Total Ecosystem Metabolism Variability in a Subtropical Lagoonal Estuary Channel-Site. Estuaries and Coasts, v. 1, p. 1, 2023.](http://dx.doi.org/10.1007/s12237-023-01270-2)

- [BORDIN, LUÍS HENRIQUE ; MACHADO, EUNICE DA C. ; MENDES, CARLOS R.B. ; FERNANDES, ELISA H.L. ; Camargo, Maurício G. ; KERR, RODRIGO ; SCHETTINI, CARLOS A. Daily variability of pelagic metabolism in a subtropical lagoonal estuary. JOURNAL OF MARINE SYSTEMS, v. 240, p. 103861. 2023](http://dx.doi.org/10.1016/j.jmarsys.2023.103861)  

- [SOUZA, FERNANDA M. ; GILBERT, ELIANDRO R. ; BRAUKO, KALINA M. ; LORENZI, LUCIANO ; MACHADO, EUNICE ; Camargo, Mauricio G. . Macrobenthic community responses to multiple environmental stressors in a subtropical estuary. PeerJ, v. 9, p. e12427. 2021](http://dx.doi.org/10.7717/peerj.12427)

- [STEIGLEDER, KARINE M. ; COPERTINO, MARGARETH S. ; LANARI, MARIANNA ; CAMARGO, MAURÍCIO ; FUJJI, MUTUE TOYOTA . Latitudinal gradient in intertidal seaweed composition off the coast of southern Brazil and Uruguay. AQUATIC BOTANY, v. 156, p. 47-56, 2019.](http://dx.doi.org/10.1016/j.aquabot.2019.04.003)

- [SANTOS-SILVA, M. C. ; MACHADO, E. C. ; CAMARGO, MAURÍCIO G. DE . Background levels of trace elements in brown and red seaweeds from Trindade, a remote island in South Atlantic Ocean. MARINE POLLUTION BULLETIN, v. 135, p. 923-931, 2018.](https://doi.org/10.1016/j.marpolbul.2018.08.019)

- [CAMARGO, MANUELA ZEGLIN ; SANDRINI-NETO, LEONARDO ; CARREIRA, RENATO S. ; Camargo, Maurício G. . Effects of hydrocarbon pollution in the structure of macrobenthic assemblages from two large estuaries in Brazil. MARINE POLLUTION BULLETIN, v. 125, p. 66-76, 2017.](https://doi.org/10.1016/j.marpolbul.2017.07.074)

- [MACHADO, E. C. ; AREVALO, P. R. ; CASARTELLI, M. R. O. ; Camargo, Mauricio Garcia ; SILVA-FILHO, E. V. . Preliminary Study about the Origin of Trace Elements in the Atmospheric Deposition in Two Brazilian Subtropical Estuaries. Journal of the Brazilian Chemical Society (Impresso), v. 27, p. 735-744, 2016.](http://dx.doi.org/10.5935/0103-5053.20150323)

- [MORAIS, GISELE C. ; Camargo, Maurício G. ; LANA, PAULO . Intertidal assemblage variation across a subtropical estuarine gradient: How good conceptual and empirical models are?. Estuarine, Coastal and Shelf Science (Print), v. 170, p. 91-101, 2016.](http://dx.doi.org/10.1016/j.ecss.2015.12.020)

- [SOUZA, F.M. ; BRAUKO, K.M. ; Gilbert, E.R. ; MARTINS, C.C. ; LANA, P.C. ; CAMARGO, M.G. . Complex spatial and temporal variation of subtropical benthic macrofauna under sewage impact. Marine Environmental Research, v. 116, p. 61-70, 2016.](http://dx.doi.org/10.1016/j.marenvres.2016.02.008)

- [Parizzi, R.A. ; MACHADO, E. C. ; Tavares, C.P.S. ; FERNANDES, L. F. ; MAFRA JUNIOR, L. L. ; CAMARGO, M.G. Primary productivity and phytoplankton dynamics in a subtropical estuary: a multiple time-scale approach. SCIENTIA MARINA, v. 80, p. 291-303, 2016.](http://dx.doi.org/10.3989/scimar.04358.26A)
- [BRAUKO, K.M. ; SOUZA, F. M. ; MACIEL, P. M. ; Camargo, Mauricio G. ; LANA, PAULO CUNHA . Spatial variability of three benthic indices for marine quality assessment in a subtropical estuary of Southern Brazil. Marine Pollution Bulletin., v. 91, p. 454-460, 2015.](http://dx.doi.org/10.1016/j.marpolbul.2014.10.025)

- [PAGLIOSA, P. R. ; DORIA, J. G. ; MISTURINI, D. ; OTEGUI, M. B. P. ; OORTMAN, M. S. ; WEIS, W. A. ; FARONI-PEREZ, L. ; ALVES, A. P. ; CAMARGO, M. G. ; AMARAL, A. C. Z. ; MARQUES, A. C. ; LANA, P. C. . NONATObase: a database for Polychaeta (Annelida) from the Southwestern Atlantic Ocean. DATABASE-OXFORD, v. 2014, p. bau002-bau002, 2014.](http://dx.doi.org/10.1093/database/bau002)

- [Camargo, Mauricio Garcia; NARDES, EMANOELA ; LANA, PAULO CUNHA . Efeitos de um derrame experimental de óleo bunker na sobrevivência e taxas de crescimento de plântulas de Laguncularia racemosa (Combretaceae). Biotemas, v. 26, p. 53-67, 2013.](http://dx.doi.org/10.5007/2175-7925.2013v26n1p53)

- [MARTINS, RODRIGO S. ; ROBERTS, MICHAEL J. ; LETT, CHRISTOPHE ; CHANG, NICOLETTE ; MOLONEY, COLEEN L. ; Camargo, Maurício G. ; VIDAL, ERICA A. G. . Modelling transport of chokka squid ( Loligo reynaudii ) paralarvae off South Africa: reviewing, testing and extending the -Westward Transport Hypothesis?. Fisheries Oceanography (Print), v. 23, p. n/a-n/a, 2013.](http://dx.doi.org/10.1111/fog.12046)

- [SOUZA, FERNANDA M. DE ; GILBERT, ELIANDRO R. ; CAMARGO, MAURÍCIO G. DE ; PIEPER, WAGNER W. . The spatial distribution of the subtidal benthic macrofauna and its relationship with environmental factors using geostatistical tools: a case study in Trapandé Bay, southern Brazil. Zoologia (Curitiba): an international journal for zoology, v. 30, p. 55-65, 2013.](http://dx.doi.org/10.1590/s1984-46702013000100007)

- [SOUZA, F.M. ; BRAUKO, K.M. ; LANA, P.C. ; MUNIZ, P. ; CAMARGO, M.G. . The effect of urban sewage on benthic macrofauna: A multiple spatial scale approach. Marine Pollution Bulletin., v. 1, p. 1-7, 2012.](http://dx.doi.org/10.1016/j.marpolbul.2012.10.021)

- [MANGO, MARIA SILVIA MARTINS ; CARILHO, MÔNICA KOPPLIN ; DRABOVSKI, BIANCA ; JOUCOSKI, EMERSON ; GARCIA, MAURÍCIO CAMARGO ; GOMES, ANNA RAQUEL SILVEIRA . Análise dos sintomas osteomusculares de professores do ensino fundamental em Matinhos (PR). Fiosterapia em Movimento (on-line), v. 25, p. 785-794, 2012.](http://dx.doi.org/10.1590/S0103-51502012000400011)

- [LOCKS, RAFAELLA R. ; COSTA, TATIANA C. ; KOPPE, SORAIA ; YAMAGUTI, ANELIZE M. ; GARCIA, MAURÍCIO C. ; GOMES, ANNA R. S. Effects of strength and flexibility training on functional performance of healthy older people. Revista Brasileira de Fisioterapia (Impresso), v. 16, p. 184-190, 2012.] (http://dx.doi.org/10.1590/S1413-35552012000300003)


- BRAUKO, K. M. ; CAMARGO, M. G. ; LANA, P. C. . A new method to assess herbivory levels on Rhizophora mangle L. fruits in mangroves with different degrees of forest complexity. Pan-American Journal of Aquatic Sciences, v. 6, p. 9-15, 2011.

- [Oliveira, V.M. ; GOMES, C. S. ; LANA, P. C. ; CAMARGO, M. G. . Morphological variations caused by fixation techniques may lead to taxonomic confusion in Laeonereis (Polychaeta, Nereididae). Zoologia (Curitiba. Impresso), v. 27, p. 146-150, 2010.](http://dx.doi.org/10.1590/s1984-46702010000100022)

- GARRAFFONI, A. ; CAMARGO, M. G. . A new application of morphometrics in a study of the variation in uncinial shape present within the Terebellidae (Polychaeta): a reevaluation from digital images.. Cahiers de Biologie Marine, v. 48, p. 229-248, 2007.

- GARRAFFONI, A. ; CAMARGO, M. G. . First application of morphometrics in a study of the variation in uncinial shape present within the Terebellidae (Polychaeta). Zoological Studies, v. 45, n.1, p. 625-630, 2006.

- CAMARGO, M. G.. SysGran: um sistema de código aberto para análises granulométricas do sedimento.. Revista Brasileira de Geociências, v. 345, p. 345-352, 2006.
Citações:13

- FONTES, M. ; CAVELLUCCI, R. ; MACHADO, E. C. ; CAMARGO, M. G. ; LAURENTI, A. . Detection of Environmental Impact on Variations in Dissolved Nutrients and Chl-a in the Conceição Lagoon, Florianópolis, Santa Catarina, Brazil. Journal of Coastal Research, v. 39, p. 1407-1412, 2005.

- MARONE, E. ; MACHADO, E. C. ; FERNANDES, L. F. ; LOMBARDI, A. T. ; KOLM, H. E. ; NOERNBERG, M. A. ; CAMARGO, M. G. . Establishment of a monitoring system for water-sediment quality in Paranaguá and Guaratuba bays, Paraná, Brazil.. International symposium on the environmental preservation of urban areas and costal zones, JICA Hyogo, Kobe, Japan, v. 1, p. 71-84, 2004.

- SCHRIJVERS, J. ; CAMARGO, M. G. ; PRATIWI, R. ; VINCX, M. . The infaunal macrobenthos under east African Ceriops tagal mangroves impacted by epibenthos.. Journal of Experimental Marine Biology and Ecology, v. 222, p. 175-193, 1998.

- LANA, P. C. ; CAMARGO, M. G. ; BROGIM, R. ; ISAAC, V. O bentos da costa brasileira: avaliação crítica e levantamento bibliográfico (1858 - 1996). MMA, CIRM e FEMAR, 1996. v. 1000. 431p.

- CAMARGO, M. G.; LANA, P. C. . Lumbrineridae (Polychaeta: Eunicemorpha) da costa sul e sudeste do Brasil. I. Lysarete, Arabelloneris, Lumbrineriopsis, Lumbrineridae, Paraninoe e Ninoe. Iheringia - Série Zoologia, Porto Alegre - RS, v. 79, p. 77-92, 1995.

- CAMARGO, M. G.; LANA, P. C. . Lumbrineridae (Polychaeta: Eunicemorpha) da costa sul e sudeste do Brasil. II. Lumbrineris.. Iheringia - Série Zoologia, Porto Alegre - RS, v. 79, p. 93-120, 1995.

- CAMARGO, M. G.; LANA, P. C. . Lumbrineridae (Polychaeta: Eunicemorpha) da costa sul e sudeste do Brasil. III. Padrões regionais e zoogeográficos de distribuição.. Nerítica, v. 8, n.1, p. 21-30, 1995.

- YUNES, J. S. ; SUZUKI, M. T. ; CAMARGO, M. G. ; SILVEIRA, A. G. ; WERNER, V. R. . Diazothrophic Growth and Nitrogenase Activity of Cyanobacteria from the Patos lagoon estuary-Southern Brazil.. Vittale, Rio Grande - RS, v. 6, p. 25-36, 1994.

- YUNES, J. S. ; SUZUKI, M. T. ; CAMARGO, M. G. ; SILVEIRA, A. G. ; WERNER, V. R. . Cianobactérias fixadoras de nitrogênio do estuário da Lagoa dos Patos, RS: Nostoc muscorum. Ciência e Cultura (SBPC), v. 42, n.5/6, p. 375-383, 1990.

:::

