---
title: "Publications"
output:
  html_document:
    toc: false
---

## Peer-reviewed publications

1. Bender, M. G.; Floeter, S. R.; Mayer, F. P.; Vila-Nova, D. A.; Longo,
G. O.; Hanazaki, N.; Carvalho-Filho, A.; Ferreira, C. E. L. 2013.
Biological attributes and major threats as predictors of the
vulnerability of species: a case study with Brazilian reef fishes.
**[Oryx][]** (Oxford Print), 47(2): 259-265.
[DOI: 10.1017/S003060531100144X][DOI].

1. Mayer, F. P. & Andrade, H. A. 2008. Size of yellowfin tuna (*Thunnus
albacares*) caught by pole-and-line fleet in the southwestern Atlantic
ocean. **[Brazilian Journal of Aquatic Science and Technology][BJAST]**,
12(1): 59-62.

1. Andrade, H. A.; Pereira, M. D. & Mayer, F. P. 2007. Alternative
methods for calculating catch-per-unit-effort for skipjack tuna
(*Katsuwonus pelamis*) caught in the southwestern Atlantic ocean.
**[Brazilian Journal of Aquatic Science and Technology][BJAST]**, 11(2):
63-66.

1. Mayer, F. P. & Andrade, H. A. 2005. Swordfish (*Xiphias gladius*) and
blue shark (*Prionace glauca*) fishery and the dynamics of the fleet off
the southeastern brazilian coast.
**[Collective Volume of Scientific Papers, ICCAT][CVSP]**. 58(3):
1204-1214.

1. Mayer, F. P., Andrade, H. A. 2003. Catch, effort and CPUE of
swordfish (*Xiphias gladius*) landed in Santa Catarina in 2000 and 2001.
**[Brazilian Journal of Aquatic Science and Technology][BJAST]** (Former
"Notas Técnicas da FACIMAR"). 7: 23-36. (*In portuguese*)

## Extended abstracts

1. Mayer, F. P.; Bonat, W. H.; Ribeiro Jr., P. J. 2011. Spatio-temporal
modelling of catches in commercial fisheries through hierarchical
Bayesian models with latent Gaussian structure. *In*:
[56 Annual Brazilian Region meeting of the International Biometric Society][RBRAS56].
(*In portuguese*).

1. Mayer, F. P. 2009. Count data models considering overdispersion and
excess zeros for abundance estimates of uncommon species in commercial
fisheries. *In*:
[54 Annual Brazilian Region meeting of the International Biometric Society][RBRAS54].
(*In portuguese*)

[Oryx]: http://journals.cambridge.org/action/displayJournal?jid=ORX
[BJAST]: http://www.univali.br/bjast
[BJAST1]: http://www6.univali.br/seer/index.php/bjast/article/viewFile/288/250
[BJAST2]: http://www6.univali.br/seer/index.php/bjast/article/viewFile/39/35
[BJAST3]: https://www6.univali.br/seer/index.php/bjast/article/view/2544/1757
[CVSP]: http://www.iccat.int/en/pubs_CVSP.htm
[ICCAT1]: http://www.iccat.int/Documents/CVSP/CV058_2005/no_3%5CCV058031204.pdf
[RBRAS56]: http://www.rbras.org.br/rbras56/
[RBRAS54]: http://www.rbras.org.br/rbras54/
[RBRAS1]: ./Mayer_et_al_RBRAS_2011.pdf
[RBRAS2]: ./Mayer_RBRAS_2009.pdf
[DOI]: http://dx.doi.org/10.1017/S003060531100144X
[ORYX1]: http://journals.cambridge.org/action/displayFulltext?type=1&fid=8893959&jid=ORX&volumeId=47&issueId=02&aid=8893957&bodyId=&membershipNumber=&societyETOCSession=
