---
title: "Truques do Quarto e Github"
engine: knitr
toc: TRUE
toc-location: left
lang: pt
---

### 1. Linha mágica para dar um `Commit` quando o RStudio trava.

No RStudio, ao selecionar os arquivos para dar um `Commit`, pode acontecer de travar o programa ou a seleção não funcionar.   

Quando não for possível dar um `Commit`, tente a seguinte linha mágica no terminal do RStudio:

```r
git add -A && git commit -m "staging all files"
```

### 2. Quando o RStudio pede para instalar o Python ou o Jupyter, do nada?

Informe no cabeçalho que a engine é a **knitr**, usando `engine: knitr`.


```default
---
title: "Título"
engine: knitr
---
```
:::aside
"Engine" é o motor de renderização (que transforma script em HTML), que pode ser o knitr (do RStudio) ou Jupyter (do Python). O padrão (default) é knitr, mas não sei porque de vez em quando temos que informar manualmente.
:::


<!-- NÃO DEU CERTO.
Não teve jeito de mostrar a primeira linha (```{css}) em markdow. A solução foi HTML

Assim não dá certo:
````{default}
```{css,  echo=FALSE}
.justify {
 text-align:
justify !important
}  
````
 ```
-->

<br>

### 3. E se eu quiser justificar um texto longo?
Para justificar um texto, pode-se usar:

```{markdown}
:::{.justify}
Testo a ser justificado. Claro que precisa ser um texto longo para testar se justifica ou não, então aqui vai um texto longo: asdasdasd sdfsdfg fghfgh rtertert dfg f fgh sd sdf sdf sd gdfgdfg serw er fgh fg hfg h sdf sdf dfg gfhjfghfg sdfsdfgdrfghdh dfgdfhgfghfghfghgf sdfsdfgfghfghgfh 
:::
```

No entanto, há um bug no RStudio e o texto não é justificado nunca.

Primeiro, é necessário usar `engine: knitr`, como mostrado no item 2.

Se não funcionar, adicione também o seguinte código em qualquer parte do seu script:

<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{css,  echo=FALSE}</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="op">.</span><span class="fu">justify</span> <span class="op">{</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a> text<span class="op">-</span>align<span class="op">:</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>justify <span class="op">!</span>important}</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="op">```</span></span></span></code></pre></div><p>


<br>

