---
title: "Atigos para o seminário"
output:
  html_document:
    toc: false
---

[1-Andrew 1993.pdf](artigos_seminario/1-Andrew 1993.pdf)  
Density-dependent foraging in the sea urchin
Centrostephanus rodgersii on shallow subtidal
reefs in New South Wales, Australia  
[2-Archambault 1996.pdf](artigos_seminario/2-Archambault 1996.pdf)  
Scales of coastal heterogeneity and benthic
intertidal species richness, diversity
and abundance  
[3-Barros 2001.pdf](artigos_seminario/3-Barros 2001.pdf)  
The Influence of Rocky Reefs on Structure of Benthic
Macrofauna in Nearby Soft-sediments  
[4-Boaventura 2002.pdf](artigos_seminario/4-Boaventura 2002.pdf)  
The effects of grazing on the distribution and
composition of low-shore algal communities on
the central coast of Portugal and on the southern
coast of Britain  
[5-Chapman 1994.pdf](artigos_seminario/5-Chapman 1994.pdf)  
Aggregation of the littorinid snail Littorina
unifasciata in New South Wales, Australia  
[6-Chapman 2010.pdf](artigos_seminario/6-Chapman 2010.pdf)  
Complex and inconsistent patterns of variation in
benthos, micro-algae and sediment over multiple
spatial scales  
[7-Charton 2004.pdf](artigos_seminario/7-Charton 2004.pdf)  
Multi-scale spatial heterogeneity, habitat structure, and the effect of marine reserves on Western Mediterranean rocky reef fish assemblages  
[8-Clarke & Ward 1994.pdf](artigos_seminario/8-Clarke & Ward 1994.pdf)  
The response of southern hemisphere saltmarsh plants and
gastropods to experimental contamination by petroleum
hydrocarbons  
[9-Clemente 2007.pdf](artigos_seminario/9-Clemente 2007.pdf)  
Predation upon Diadema aff. antillarum in barren grounds in the Canary Islands  
[10-Commito 2006.pdf](artigos_seminario/10-Commito 2006.pdf)  
Hierarchical spatial structure in soft-bottom mussel beds  
[11-Crowe 1999.pdf](artigos_seminario/11-Crowe 1999.pdf)  
Limits to generality: seasonal and temporal variation in
dispersal of an intertidal gastropod   
[12-Dempster 2002.pdf](artigos_seminario/12-Dempster 2002.pdf)  
Attraction of wild fish to sea-cage fish farms in the south-western Mediterranean Sea: spatial and short-term temporal variability  
[13-Dempster 2005.pdf](artigos_seminario/13-Dempster 2005.pdf)     
Vertical variability of wild fish assemblages around
sea-cage fish farms: implications for management     
[14-Di Domenico 2009.pdf](artigos_seminario/14-Di Domenico 2009.pdf)   
 **Reservado Fernando**  
Distribution patterns of interstitial polychaetes in sandy
beaches of southern Brazil  
[15-Eggleston 1998.pdf](artigos_seminario/15-Eggleston 1998.pdf)  
Organism response to habitat patchiness: species and habitat-
dependent recruitment of decapod crustaceans  
[16-Fraschetti 2001.pdf](artigos_seminario/16-Fraschetti 2001.pdf)  
Spatial variability and human disturbance in shallow subtidal hard substrate assemblages: a regional approach  
[17-Gray 1996.pdf](artigos_seminario/17-Gray 1996.pdf)  
**Reservado Priscila**  
Small-scale temporal variability in assemblages of larval fishes: implications for sampling  
[18-Gray 2009.pdf](artigos_seminario/18-Gray 2009.pdf)  
Spatial scales of variation of assemblages of fish in coastal lakes sampled with multi-mesh gillnets: Implications for designing research surveys  
[19-Hernandez 2006.pdf](artigos_seminario/19-Hernandez 2006.pdf)  
Spatial and seasonal variation of the gonad index of Diadema antillarum (Echinodermata: Echinoidea) in the Canary Islands  
[20-Lindegarth 2001.pdf](artigos_seminario/20-Lindegarth 2001.pdf)  
**Reservado Camila**  
Patterns of Distribution of Macro-fauna in Different Types of Estuarine, Soft Sediment Habitats Adjacent to Urban and Non-urban Areas  
[21-Morais 2003.pdf](artigos_seminario/21-Morais 2003.pdf)  
Gonad development and fatty acid composition of Patella depressa Pennant (Gastropoda: Prosobranchia) populations with different patterns of spatial distribution, in exposed and sheltered sites  
[22-Morrisey 2003.pdf](artigos_seminario/22-Morrisey 2003.pdf)  
Factors affecting the distribution of benthic macrofauna in estuaries contaminated
by urban runoff  
[23-Morrisey Espacial 1992.pdf](artigos_seminario/23-Morrisey Espacial 1992.pdf)  
Spatial variation in soft-sediment benthos  
[24-Morrisey Temporal 1992.pdf](artigos_seminario/24-Morrisey Temporal 1992.pdf)  
Temporal variation in soft-sediment benthos  
[25-Murphy 2009.pdf](artigos_seminario/25-Murphy 2009.pdf)  
Seasonal distribution of chlorophyll on mudflats in New South Wales, Australia measured by field spectrometry and PAM fluorometry  
[26-Negrello-Filho 2006.pdf](artigos_seminario/26-Negrello-Filho 2006.pdf)  
Recolonization of infauna on a tidal flat: An experimental analysis
of modes of dispersal  
[27-Noren 2005.pdf](artigos_seminario/27-Noren 2005.pdf)  
Spatial, temporal and interactive variability of infauna in Swedish coastal sediments   
[28-Olabarria 2001.pdf](artigos_seminario/28-Olabarria 2001.pdf)  
Comparison of patterns of spatial variation of microgastropods between two contrasting intertidal habitats  
[29-Olabarria 2002.pdf](artigos_seminario/29-Olabarria 2002.pdf)  
Role of colonization in spatio-temporal patchiness of microgastropods in coralline turf habitat  
[30-Olabarria 2009.pdf](artigos_seminario/30-Olabarria 2009.pdf)  
**Reservado Nicholas**  
Use of hierarchical designs to detect scales of heterogeneity in the invasive species Sargassum muticum  
[31-Paiva 2001.pdf](artigos_seminario/31-Paiva 2001.pdf)  
Spatial and Temporal Variation of a Nearshore Benthic Community in Southern Brazil: Implications for the Design of Monitoring Programs  
[32-Perez-ruzafa 2007.pdf](artigos_seminario/32-Perez-ruzafa 2007.pdf)  
Detecting changes resulting from human pressure in a naturally quick-changing and heterogeneous environment: Spatial and temporal scales of variability in coastal lagoons  
[33-Rajasekharan 2007.pdf](artigos_seminario/33-Rajasekharan 2007.pdf)  
Intrinsic differences in dispersal between populations of gastropods
separated by a few metres: Evidence from reciprocal experimental transplantation  
[34-Rindi 2002.pdf](artigos_seminario/34-Rindi 2002.pdf)  
DIVERSITY, LIFE HISTORY, AND ECOLOGY OF TRENTEPOHLIA AND PRINTZINA (TRENTEPOHLIALES, CHLOROPHYTA) IN URBAN HABITATS IN WESTERN IRELAND  
[35-Ruiz & Romero 2001.pdf](artigos_seminario/35-Ruiz & Romero 2001.pdf)  
Effects of in situ experimental shading on the Mediterranean seagrass Posidonia oceanica  
[36-Salovius .pdf](artigos_seminario/36-Salovius .pdf)  
THE FILAMENTOUS GREEN ALGA CLADOPHORA GLOMERAT A AS A HABITAT FOR LITTORAL MACRO-
FAUNA IN THE NORTHERN BALTIC SEA  
[37-Boaventura 2002.pdf](artigos_seminario/37-Boaventura 2002.pdf)  
The effects of grazing on the distribution and composition of low-shore algal communities on the central coast of Portugal and on the southern
coast of Britain  
[38-Vannini 2008.pdf](artigos_seminario/38-Vannini 2008.pdf)  
Rhythmic vertical migration of the gastropod Cerithidea decollata
in a Kenyan mangrove forest  
[39-Ysebaert 2002.pdf](artigos_seminario/39-Ysebaert 2002.pdf)  
Spatial and temporal variation in benthic macrofauna and relationships with environmental variables in an estuarine, intertidal soft-sediment environment  
[40-Chapman 1994.pdf](artigos_seminario/40-Chapman 1994.pdf)  
Aggregation of the littorinid snail Littorina unifasciata in New South Wales, Australia  
[40a-Hughes 1999.pdf](artigos_seminario/40-Hughes 1999.pdf)  
Patterns of recruitment and abundance of corals along the Great Barrier Reef  
[41-Chapman 2010.pdf](artigos_seminario/41-Chapman 2010.pdf)  
Complex and inconsistent patterns of variation in benthos, micro-algae and sediment over multiple spatial scales  
[42-Charton 2004.pdf](artigos_seminario/42-Charton 2004.pdf)  
Multi-scale spatial heterogeneity, habitat structure, and the effect of
marine reserves on Western Mediterranean rocky reef fish assemblages  
[43-Clarke & Ward 1994.pdf](artigos_seminario/43-Clarke & Ward 1994.pdf)   
The response of southern hemisphere saltmarsh plants and gastropods to experimental contamination by petroleum hydrocarbons  
[44-Clemente 2007.pdf](artigos_seminario/44-Clemente 2007.pdf)  
Predation upon Diadema aff. antillarum in barren grounds in the Canary Islands  
[45-Boaventura 2002.pdf](artigos_seminario/45-Boaventura 2002.pdf)  
The effects of grazing on the distribution and composition of low-shore algal communities on the central coast of Portugal and on the southern coast of 
Britain  
[46-Cannicci etal 2009.pdf](artigos_seminario/46-Cannicci etal 2009.pdf)  
**Reservado Andréa**  
Effects of urban wastewater on crab and mollusc assemblages in equatorial and
subtropical mangroves of East Africa  
[47-Guichard 2001.pdf](artigos_seminario/47-Guichard 2001.pdf)  
Scaling the influence of topographic heterogeneity on intertidal benthic communities: alternate trajectories mediated by hydrodynamics and shading  
[48-Henry Jenkins 1995.pdf](artigos_seminario/48-Henry Jenkins 1995.pdf)  
The impact of predation by the girdled goby, Nesogobiu sp. on abundances of meiofauna ans small macrofauna.
[49-Lourenço-McKinley 2011.pdf](artigos_seminario/49-Lourenço-McKinley 2011.pdf)  
Strong links between metal contamination, habitat modification and estuarine larval fish distributions  
[50-Underwood 1999.pdf](artigos_seminario/50-Underwood 1999.pdf)  
**Reservado Ana Carolina**  
Physical disturbances and their direct effect on an indirect effect: responses of an intertidal assemblage to a severe storm  
[51-Winberg 2007.pdf](artigos_seminario/51-Winberg 2007.pdf)  
The importance of spatial scale for the conservation of tidal flat macrobenthos: An example from New South Wales, Australia  
[52-James e Fairweather 1996.pdf](artigos_seminario/52-James e Fairweather 1996.pdf)  
Spatial Variation of Intertidal Macrofauna on a Sandy Ocean Beach in Australia  
[53-Neves2012.pdf](artigos_seminario/53-Neves2012.pdf)  
Factors influencing spatial patterns of molluscs in a eutrophic tropical
bay  
[54-Camargo 2017.pdf](artigos_seminario/54-Camargo 2017.pdf)  
Effects of hydrocarbon pollution in the structure of macrobenthic
assemblages from two large estuaries in Brazil  
