---
title: "Hidroweb"
---

***
Vamos primeiramente abrir o arquivo  vazoes_T_87905000.txt, que foi baixado do site hidroweb.
\newline
```{r}
library(readr)
ArqTxtPath='vazoes_T_87905000.txt'
ArqTxt=read_lines(ArqTxtPath,skip=13)
ArqTxt[1]=paste0(ArqTxt[1],';') #Inserindo ";" na primeira linha para evitar problemas com row.names
ArqCsvPath=gsub('txt','csv',ArqTxtPath)
write_lines(ArqTxt,ArqCsvPath)
dados=read.table(ArqCsvPath,header=T,sep=';',dec=',')
cat('Imprimindo parte dos dados...')
print(dados[1:5,1:5])
```
\newline
Criando coluna com tipo datetime e plotando:
```{r fig.width=10, warning=FALSE}
dados$dataN=as.POSIXct(dados$Data,format = "%d/%m/%Y")
plot(dados$Maxima~dados$dataN,type='line')
```
\newline
Criando coluna dos meses:
```{r}
dados$mes = format(dados$dataN,format='%m')
```
\newline
Extraindo a media e dp:
```{r}
media=aggregate(dados$Maxima,list(Mes=dados$mes),mean,na.rm=T)
dp=aggregate(dados$Maxima,list(dados$mes),sd,na.rm=T)
```
\newline
Calculando desvio superior e inferior:
```{r}
mediaMais=media$x+dp$x
mediaMenos=media$x-dp$x
```
\newline
Plot final:
```{r fig.width=10,paged.print=FALSE}
plot(media$Mes,media$x, ty="l", col="blue", 
     ylab='Vazão', 
     xlab='Meses',
     lty=1,lwd=3,
     ylim=c(-1000,3000))
lines(media$Mes, mediaMais, col='gray')
lines(media$Mes, mediaMenos, col='gray')
polygon(x=c(media$Mes, rev(media$Mes)), y=c(mediaMais, rev(mediaMenos)), col="lightblue", density = 40, angle=60)
lines(media$Mes, media$x)
points(media$Mes, media$x,pch=19)
```
